### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by IgorLockyh** [IgorLockyh/laratoon#5]
## Testing
- [ ] Make factories (optionally) deterministic (?)
- [ ] Write tests for API Requests
  - [x] Likes
  - [ ] Views
  - [ ] Comic user lists

- [ ] Write Laravel Dusk browser tests for simple workflows with SPA
  - [ ] adding/removing like -> like appears/disappears AND like-count changes accordingly
  - [ ] adding comment -> comment appears in (user-profile AND comments-section)
  - [ ] adding/moving/removing comic to comic-list -> comic appears in the list
  - [ ] Catalog filters applying/reseting works

## Other
- [ ] Make notification component, push user-related error messages into it
- [ ] Make less ugly header for chapter viewer
